name: Deploy to Production

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/rosantibikemotorent/backend
            
            # Backup .env
            if [ -f .env ]; then
              cp .env .env.backup
            fi
            
            # Pull latest changes
            git pull
            
            # Restore .env
            if [ -f .env.backup ]; then
              cp .env.backup .env
            fi
            
            # Deploy dengan Docker
            docker compose down
            docker compose build --no-cache
            docker compose up -d
            
            # Tunggu beberapa detik agar container siap
            sleep 10
            
            # Jalankan database migrations
            docker compose exec -T app npx prisma migrate deploy
            
            # Cleanup unused Docker resources
            docker system prune -af --volumes
            
            # Tampilkan status container
            docker compose ps 