name: Deploy ke VPS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build aplikasi
        run: pnpm run build

      - name: Generate Prisma client
        run: pnpm exec prisma generate

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Tambahkan host ke known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.SSH_PORT || 22 }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy ke VPS
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT || 22 }}
        run: |
          # Kompres untuk deployment
          tar -czf deploy.tar.gz dist/ node_modules/ package.json ecosystem.config.js prisma/ .env.example

          # Transfer ke VPS
          scp -P $SSH_PORT deploy.tar.gz $SSH_USER@$SSH_HOST:/tmp/

          # Buat script deployment
          cat > deploy.sh << 'EOFSCRIPT'
          #!/bin/bash
          mkdir -p /var/www/rosantibikemotorent/backend

          if [ -f /var/www/rosantibikemotorent/backend/.env ]; then
            cp /var/www/rosantibikemotorent/backend/.env /var/www/rosantibikemotorent/backend/.env.backup
          fi

          tar -xzf /tmp/deploy.tar.gz -C /var/www/rosantibikemotorent/backend

          if [ -f /var/www/rosantibikemotorent/backend/.env.backup ]; then
            cp /var/www/rosantibikemotorent/backend/.env.backup /var/www/rosantibikemotorent/backend/.env
          else
            cp /var/www/rosantibikemotorent/backend/.env.example /var/www/rosantibikemotorent/backend/.env
            sed -i 's/localhost:5432/localhost:5432/g' /var/www/rosantibikemotorent/backend/.env
          fi

          cd /var/www/rosantibikemotorent/backend
          npx prisma migrate deploy

          mkdir -p /var/www/rosantibikemotorent/backend/logs
          mkdir -p /var/www/rosantibikemotorent/backend/storage

          if pm2 list | grep -q "rental-backend"; then
            pm2 reload ecosystem.config.js --env production
          else
            pm2 start ecosystem.config.js --env production
          fi

          pm2 save

          rm /tmp/deploy.tar.gz

          echo "Deployed at $(date)" >> /var/www/rosantibikemotorent/deploy.log
          EOFSCRIPT

          # Transfer script ke VPS
          scp -P $SSH_PORT deploy.sh $SSH_USER@$SSH_HOST:/tmp/

          # Jalankan script di VPS
          ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "chmod +x /tmp/deploy.sh && /tmp/deploy.sh && rm /tmp/deploy.sh"
